### ISSUE TITLE
For production: Create a hosted Azure SQL database on Azure

### ISSUE THREAD

**Issue by Juules32** [ITU-BDSA23-GROUP3/Chirp#102]
See for example this guide: https://learn.microsoft.com/en-us/azure/azure-sql/database/single-database-create-quickstart?view=azuresql&tabs=azure-portal

Configure your Chirp! applications that are deployed to Azure App Service, i.e., your applications in production, to target this Azure SQL database.

The name of your database server is bdsagroup<no>-chirpdb, where <no> is replaced with your group number.

Remember to configure your Azure SQL Server to use SQL Login with a username and password to use for your connection string.

Note: The demo using Entra ID Groups and Managed Identity is not posible with your Azure Subscription on the ITU tenant. This is why we switch back to legacy SQL Login.

**Comment by AlbertRossJoh** [comment]
This issue has been resolved in commit: 819dd16df7f49ffe480e6bd015aa167ea3b9b0ed
