### ISSUE TITLE
Restructure project

### ISSUE THREAD

**Issue by felaitu** [ITU-BDSA23-GROUP3/Chirp#12]
**User story**
I want to refactor the entire project such that the Chirp application and CSV database library reside under a `src/` folder, and tests under a `test/`. I want to do this to improve the structure of the code and thereby enhance its readability and maintainability.

**Definition of Done (DoD)**
- All source code is moved to `src/`, which needs to be created
- Create `test/`, such that future unit, and integration tests can be placed there

**Comment by NatalieClaraPetersen** [comment]
Looks good!

**Comment by NatalieClaraPetersen** [comment]
Closed!
