### ISSUE TITLE
Refactor Chirp.CLI's Program.cs so that all User Interface code resides in a separate class

### ISSUE THREAD

**Issue by NatalieClaraPetersen** [ITU-BDSA23-GROUP3/Chirp#14]
**User story**
As a software developer,
I want to refactor the 'User Interface' related code from the Chirp.CLI into a separate class: UserInterface,
to improve the structure of the code and thereby enhance its maintainability by separation of concerns.

**Acceptance criteria**
**Separation of Concerns:** Separating the UI into its own class to isolate the code responsible for user interaction from the core business logic of the application.

**Definition of Done (DoD)**
The readability should be enhanced, and the responsibility for the new class should be very clear.
All team members are comfortable with the changes introduced during refactoring.
The refactoring doesn't cause any errors.

**Comment by felaitu** [comment]
This was done in the following pull request! [PR15](https://github.com/ITU-BDSA23-GROUP3/Chirp/pull/15). closing this now:)
