### ISSUE TITLE
Implement external library CLI interface

### ISSUE THREAD

**Issue by NatalieClaraPetersen** [ITU-BDSA23-GROUP3/Chirp#2]
In order to make the program less error prone when parsing arguments, as a developer, i can refactor Chirp.CLI's Program.cs to use an external library CLI interface.

Acceptance criteria:
- Use an external library CLI interface (eg. CommandLine, CommandLine, docopt.net)

**Comment by AlbertRossJoh** [comment]
This has been resolved in the following [PR](https://github.com/ITU-BDSA23-GROUP3/Chirp/pull/5)
