### ISSUE TITLE
Add SQLite3 filebased database

### ISSUE THREAD

**Issue by felaitu** [ITU-BDSA23-GROUP3/Chirp#39]
Retire our current CSV database, and opt for using an ORM database, specifically SQLite3.

**Acceptance criteria**
Add a SQLite3 database, which should replace the CSV database

**Definition of Done (DoD)**
It should be possible to read Cheeps from an SQLite3 file based database, and also write to the SQLite3 database. If possible use DI when using the database. Make sure prepared statements are used when needed, such that we don't see any SQL injections.

**Comment by sumrdev** [comment]
This is done
