### ISSUE TITLE
In order to automate the development proces, add github workflows

### ISSUE THREAD

**Issue by Juules32** [ITU-BDSA23-GROUP3/Chirp#48]
Acceptance Criteria:
- A workflow for automatically testing and building on merges or pulls should work
- A workflow for automatically deploying to Azure should work
- A workflow for automatic releases when git tag is used should work

**Comment by sumrdev** [comment]
Automatic deployment to azure works and releases thanks to @AlbertRossJoh 
I will now look at making sure we test the code before it lands on the cloud
