### ISSUE TITLE
Refactor data persistence to library project SimpleDB

### ISSUE THREAD

**Issue by NatalieClaraPetersen** [ITU-BDSA23-GROUP3/Chirp#6]
**User story**
As a software developer, 
I want to refactor the 'data persistence' from the Chirp.CLI into a separate library project: SimpleDB,
to improve the structure of the code and thereby enhance its readability and maintainability.

**Acceptance criteria**
- _Single Responsibility Principle:_ Code should be abstracted into **reusable** components.
- _Dependency injection:_ Appropriate use of Interfaces to reduce coupling.

**Definition of Done (DoD)**
- All team members are comfortable with the changes introduced during refactoring.
- The refactoring doesn't cause any errors.

**Comment by felaitu** [comment]
Done!
